services:
  postgres:
    image: postgres:15
    container_name: tp2-db
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "database"
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema/schema.sql:/docker-entrypoint-initdb.d/init.sql #entry point para inicializar la base de datos con el script schema.sql
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:
