// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Libro struct {
	ID               int32     `json:"id"`
	Titulo           string    `json:"titulo"`
	Autor            string    `json:"autor"`
	FechaPublicacion time.Time `json:"fecha_publicacion"`
	Genero           string    `json:"genero"`
}

type Usuario struct {
	ID              int32     `json:"id"`
	Nombre          string    `json:"nombre"`
	Apellido        string    `json:"apellido"`
	Email           string    `json:"email"`
	Password        string    `json:"password"`
	FechaNacimiento time.Time `json:"fecha_nacimiento"`
}

type UsuarioLibro struct {
	UsuarioID    int32        `json:"usuario_id"`
	LibroID      int32        `json:"libro_id"`
	Leido        bool         `json:"leido"`
	FechaLectura sql.NullTime `json:"fecha_lectura"`
}
