// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createLibro = `-- name: CreateLibro :one
INSERT INTO libro (titulo, autor, fecha_publicacion, genero) 
VALUES ($1, $2, $3, $4) RETURNING id, titulo, autor, fecha_publicacion, genero
`

type CreateLibroParams struct {
	Titulo           string    `json:"titulo"`
	Autor            string    `json:"autor"`
	FechaPublicacion time.Time `json:"fecha_publicacion"`
	Genero           string    `json:"genero"`
}

func (q *Queries) CreateLibro(ctx context.Context, arg CreateLibroParams) (Libro, error) {
	row := q.db.QueryRowContext(ctx, createLibro,
		arg.Titulo,
		arg.Autor,
		arg.FechaPublicacion,
		arg.Genero,
	)
	var i Libro
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Autor,
		&i.FechaPublicacion,
		&i.Genero,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one


INSERT INTO usuario (nombre, apellido, email, password, fecha_nacimiento)
VALUES ($1, $2, $3, $4, $5) RETURNING id, nombre, apellido, email, password, fecha_nacimiento
`

type CreateUserParams struct {
	Nombre          string    `json:"nombre"`
	Apellido        string    `json:"apellido"`
	Email           string    `json:"email"`
	Password        string    `json:"password"`
	FechaNacimiento time.Time `json:"fecha_nacimiento"`
}

// CRUD
// Create
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Nombre,
		arg.Apellido,
		arg.Email,
		arg.Password,
		arg.FechaNacimiento,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Email,
		&i.Password,
		&i.FechaNacimiento,
	)
	return i, err
}

const createUsuarioLibro = `-- name: CreateUsuarioLibro :one
INSERT INTO usuario_libro (usuario_id, libro_id, leido) 
VALUES ($1, $2, $3) RETURNING usuario_id, libro_id, leido, fecha_lectura
`

type CreateUsuarioLibroParams struct {
	UsuarioID int32 `json:"usuario_id"`
	LibroID   int32 `json:"libro_id"`
	Leido     bool  `json:"leido"`
}

func (q *Queries) CreateUsuarioLibro(ctx context.Context, arg CreateUsuarioLibroParams) (UsuarioLibro, error) {
	row := q.db.QueryRowContext(ctx, createUsuarioLibro, arg.UsuarioID, arg.LibroID, arg.Leido)
	var i UsuarioLibro
	err := row.Scan(
		&i.UsuarioID,
		&i.LibroID,
		&i.Leido,
		&i.FechaLectura,
	)
	return i, err
}

const deleteLibro = `-- name: DeleteLibro :exec
DELETE FROM libro
WHERE id = $1
`

func (q *Queries) DeleteLibro(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteLibro, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec

DELETE FROM usuario
WHERE id = $1
`

// Delete
func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUsuarioLibro = `-- name: DeleteUsuarioLibro :exec
DELETE FROM usuario_libro
WHERE usuario_id = $1 AND libro_id = $2
`

type DeleteUsuarioLibroParams struct {
	UsuarioID int32 `json:"usuario_id"`
	LibroID   int32 `json:"libro_id"`
}

func (q *Queries) DeleteUsuarioLibro(ctx context.Context, arg DeleteUsuarioLibroParams) error {
	_, err := q.db.ExecContext(ctx, deleteUsuarioLibro, arg.UsuarioID, arg.LibroID)
	return err
}

const getAllLibros = `-- name: GetAllLibros :many
SELECT id, titulo, autor, fecha_publicacion, genero FROM libro
`

func (q *Queries) GetAllLibros(ctx context.Context) ([]Libro, error) {
	rows, err := q.db.QueryContext(ctx, getAllLibros)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Libro
	for rows.Next() {
		var i Libro
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Autor,
			&i.FechaPublicacion,
			&i.Genero,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsuarios = `-- name: GetAllUsuarios :many
SELECT id, nombre, apellido, email, password, fecha_nacimiento FROM usuario
`

func (q *Queries) GetAllUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Apellido,
			&i.Email,
			&i.Password,
			&i.FechaNacimiento,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLibroByID = `-- name: GetLibroByID :one
SELECT id, titulo, autor, fecha_publicacion, genero FROM libro WHERE id = $1
`

func (q *Queries) GetLibroByID(ctx context.Context, id int32) (Libro, error) {
	row := q.db.QueryRowContext(ctx, getLibroByID, id)
	var i Libro
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Autor,
		&i.FechaPublicacion,
		&i.Genero,
	)
	return i, err
}

const getLibrosLeidosPorUsuario = `-- name: GetLibrosLeidosPorUsuario :many
SELECT l.id, l.titulo, l.autor, l.fecha_publicacion, l.genero 
FROM libro l JOIN usuario_libro ul ON l.id = ul.libro_id
WHERE ul.usuario_id = $1 AND ul.leido = true
`

func (q *Queries) GetLibrosLeidosPorUsuario(ctx context.Context, usuarioID int32) ([]Libro, error) {
	rows, err := q.db.QueryContext(ctx, getLibrosLeidosPorUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Libro
	for rows.Next() {
		var i Libro
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Autor,
			&i.FechaPublicacion,
			&i.Genero,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, nombre, apellido, email, password, fecha_nacimiento FROM usuario WHERE id = $1
`

// Read
func (q *Queries) GetUserByID(ctx context.Context, id int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Email,
		&i.Password,
		&i.FechaNacimiento,
	)
	return i, err
}

const getUsuariosPorLibro = `-- name: GetUsuariosPorLibro :many
SELECT u.id, u.nombre, u.apellido, u.email, u.password, u.fecha_nacimiento
FROM usuario u JOIN usuario_libro ul ON u.id = ul.usuario_id
WHERE ul.libro_id = $1 AND ul.leido = true
`

func (q *Queries) GetUsuariosPorLibro(ctx context.Context, libroID int32) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, getUsuariosPorLibro, libroID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Apellido,
			&i.Email,
			&i.Password,
			&i.FechaNacimiento,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEstadoUsuarioLibro = `-- name: UpdateEstadoUsuarioLibro :exec

UPDATE usuario_libro
SET leido = $1, fecha_lectura = CURRENT_TIMESTAMP
WHERE usuario_id = $2 AND libro_id = $3
`

type UpdateEstadoUsuarioLibroParams struct {
	Leido     bool  `json:"leido"`
	UsuarioID int32 `json:"usuario_id"`
	LibroID   int32 `json:"libro_id"`
}

// Update
func (q *Queries) UpdateEstadoUsuarioLibro(ctx context.Context, arg UpdateEstadoUsuarioLibroParams) error {
	_, err := q.db.ExecContext(ctx, updateEstadoUsuarioLibro, arg.Leido, arg.UsuarioID, arg.LibroID)
	return err
}
